### ISSUE TITLE
Inner Scrolling Question

### ISSUE THREAD

**Issue by sos0** [karl-run/react-bottom-scroll-listener#7]
Hello! I have a small fixed height container that has an inner scrolling element that I need to attach this listener to. Can you show me an example of what the `children` prop accepts and how I should set up my components to achieve this? Thanks so much.

**Comment by sos0** [comment]
Upon reading the library it seems like this feature doesn't exist yet-- am I correct in understanding this? If so, would you have time to add this feature?

**Comment by karl-run** [comment]
You are correct in that this feature isn't supported yet. I've thought about it but haven't had use for it my self.

However, adding this feature should be pretty straight forward, adding a optional prop that will be used to attach the scroll listener to, if it's not passed it simply uses the document body as now.

If you don't want to open a PR I could add this pretty soon.

**Comment by karl-run** [comment]
It wasn't as straight forward as I thought. :fearful: 

But I have published a beta, can you try it out?

`npm i react-bottom-scroll-listener@beta`

How to use the new feature: https://github.com/karl-run/react-bottom-scroll-listener#on-bottom-of-specific-container

**Comment by sos0** [comment]
It still activated when the outermost div was scrolled to the bottom

**Comment by sos0** [comment]
I just tried with a clean install with the beta version and double-checked that I had a new index.js with the updated logic. Still no luck!

**Comment by karl-run** [comment]
Can you show me how you are using it?

**Comment by sos0** [comment]
Thanks for the updated implementation link. When the README said `ref` I thought it was referring to refs created from `React.createRef()` and that's what I had passed into the props of the component. I followed your example and it worked great!

**Comment by karl-run** [comment]
Cool! Any suggestions on how to be more clear in the documentation?

**Comment by sos0** [comment]
I personally just needed to read the whole file :)
Perhaps to avoid confusion with the React.createRef, we can change the parameter being passed to some other variable name.

**Comment by karl-run** [comment]
Great. I updated the README and published a release. :)
